name: Release

on:
  release:
    types: [published]

jobs:
  slack-notification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: Get description
        id: description
        run: echo "description=$(echo ${{ toJSON(github.event.release.body) }}" >> $$GITHUB_OUTPUT
      - name: curl notification
        run: |
          curl -d '{"text": "<!channel>\n>POS Release *${{ github.event.release.tag_name }}* published \n ${{ steps.description.outputs.description }}"}' -H 'Content-Type: application/json' ${{ secrets.SLACK_WEBHOOK_EX }}