name: Release

on:
  release:
    types: [published]

jobs:
  slack-notification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: curl notification
        run: |
          echo ${{ toJSON(github.event.release.body) }}